stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
    - docker build -t registry.gitlab.com/safesoul/global-admin-portal .
    - docker push registry.gitlab.com/safesoul/global-admin-portal

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - ssh root@$SERVER_IP "cd /var/www/global-admin-portal && docker pull registry.gitlab.com/your-namespace/your-project:latest && docker-compose down && docker-compose up -d"
